"""initial schema

Revision ID: 0584a8d79225
Revises: 
Create Date: 2026-07-24 23:09:11.115978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0584a8d79225'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_table('data_quality_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('check_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_results_pipeline_run_id'), 'data_quality_results', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_data_quality_results_table_name'), 'data_quality_results', ['table_name'], unique=False)
    op.create_table('data_source_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('access_type', sa.String(length=24), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_data_source_registry_category'), 'data_source_registry', ['category'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pipeline_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('records_in', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_uuid')
    )
    op.create_index(op.f('ix_pipeline_runs_pipeline_name'), 'pipeline_runs', ['pipeline_name'], unique=False)
    op.create_table('sector_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('sector_name', sa.String(length=128), nullable=False),
    sa.Column('subsector_code', sa.String(length=32), nullable=True),
    sa.Column('subsector_name', sa.String(length=128), nullable=True),
    sa.Column('metrics_config_key', sa.String(length=64), nullable=False),
    sa.Column('valuation_config_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_code')
    )
    op.create_table('training_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data_period_start', sa.Date(), nullable=True),
    sa.Column('data_period_end', sa.Date(), nullable=True),
    sa.Column('validation_scheme', sa.String(length=32), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('git_commit', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_runs_model_name'), 'training_runs', ['model_name'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=False),
    sa.Column('sector_registry_id', sa.Integer(), nullable=True),
    sa.Column('listing_board', sa.String(length=32), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('ipo_flag_limited_history', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('free_float_pct', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['sector_registry_id'], ['sector_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('industry_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_code', sa.String(length=64), nullable=False),
    sa.Column('series_name', sa.String(length=256), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_code', 'observation_date', 'source_id', name='uq_industry_series_obs')
    )
    op.create_index(op.f('ix_industry_series_available_at'), 'industry_series', ['available_at'], unique=False)
    op.create_index(op.f('ix_industry_series_observation_date'), 'industry_series', ['observation_date'], unique=False)
    op.create_index(op.f('ix_industry_series_period_end'), 'industry_series', ['period_end'], unique=False)
    op.create_index(op.f('ix_industry_series_series_code'), 'industry_series', ['series_code'], unique=False)
    op.create_index(op.f('ix_industry_series_source_id'), 'industry_series', ['source_id'], unique=False)
    op.create_table('macro_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_code', sa.String(length=64), nullable=False),
    sa.Column('series_name', sa.String(length=256), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_code', 'observation_date', 'source_id', name='uq_macro_series_obs')
    )
    op.create_index(op.f('ix_macro_series_available_at'), 'macro_series', ['available_at'], unique=False)
    op.create_index(op.f('ix_macro_series_observation_date'), 'macro_series', ['observation_date'], unique=False)
    op.create_index(op.f('ix_macro_series_period_end'), 'macro_series', ['period_end'], unique=False)
    op.create_index(op.f('ix_macro_series_series_code'), 'macro_series', ['series_code'], unique=False)
    op.create_index(op.f('ix_macro_series_source_id'), 'macro_series', ['source_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=24), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('training_run_id', sa.Integer(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['training_run_id'], ['training_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_name'), 'model_versions', ['model_name'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_snippet', sa.Text(), nullable=True),
    sa.Column('media_name', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('credibility_tier', sa.Integer(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('cross_source_confirmed', sa.Boolean(), nullable=False),
    sa.Column('title_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_index(op.f('ix_news_articles_available_at'), 'news_articles', ['available_at'], unique=False)
    op.create_index(op.f('ix_news_articles_media_name'), 'news_articles', ['media_name'], unique=False)
    op.create_index(op.f('ix_news_articles_period_end'), 'news_articles', ['period_end'], unique=False)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_source_id'), 'news_articles', ['source_id'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('previous_ticker', sa.String(length=16), nullable=True),
    sa.Column('previous_name', sa.String(length=256), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('ratio_or_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('details', sa.String(length=512), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_available_at'), 'corporate_actions', ['available_at'], unique=False)
    op.create_index(op.f('ix_corporate_actions_company_id'), 'corporate_actions', ['company_id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_period_end'), 'corporate_actions', ['period_end'], unique=False)
    op.create_index(op.f('ix_corporate_actions_source_id'), 'corporate_actions', ['source_id'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('dividend_type', sa.String(length=16), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('cum_date', sa.Date(), nullable=True),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('amount_per_share', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fiscal_period', sa.String(length=16), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_available_at'), 'dividends', ['available_at'], unique=False)
    op.create_index(op.f('ix_dividends_company_id'), 'dividends', ['company_id'], unique=False)
    op.create_index(op.f('ix_dividends_ex_date'), 'dividends', ['ex_date'], unique=False)
    op.create_index(op.f('ix_dividends_period_end'), 'dividends', ['period_end'], unique=False)
    op.create_index(op.f('ix_dividends_source_id'), 'dividends', ['source_id'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ratio_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('computation_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_ratios_available_at'), 'financial_ratios', ['available_at'], unique=False)
    op.create_index(op.f('ix_financial_ratios_company_id'), 'financial_ratios', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_ratios_period_end'), 'financial_ratios', ['period_end'], unique=False)
    op.create_index(op.f('ix_financial_ratios_ratio_name'), 'financial_ratios', ['ratio_name'], unique=False)
    op.create_index(op.f('ix_financial_ratios_source_id'), 'financial_ratios', ['source_id'], unique=False)
    op.create_table('financial_statements_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(length=16), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('auditor_opinion', sa.String(length=64), nullable=True),
    sa.Column('going_concern_flag', sa.Boolean(), nullable=False),
    sa.Column('statement_currency', sa.String(length=3), nullable=False),
    sa.Column('scale', sa.String(length=16), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_raw_available_at'), 'financial_statements_raw', ['available_at'], unique=False)
    op.create_index(op.f('ix_financial_statements_raw_company_id'), 'financial_statements_raw', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_raw_period_end'), 'financial_statements_raw', ['period_end'], unique=False)
    op.create_index(op.f('ix_financial_statements_raw_source_id'), 'financial_statements_raw', ['source_id'], unique=False)
    op.create_table('fundamental_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_features_as_of_date'), 'fundamental_features', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_fundamental_features_company_id'), 'fundamental_features', ['company_id'], unique=False)
    op.create_index(op.f('ix_fundamental_features_feature_name'), 'fundamental_features', ['feature_name'], unique=False)
    op.create_table('market_prices_clean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('adjustment_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('is_outlier_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_missing_trading_day_filled', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'trade_date', name='uq_price_clean_company_date')
    )
    op.create_index(op.f('ix_market_prices_clean_available_at'), 'market_prices_clean', ['available_at'], unique=False)
    op.create_index(op.f('ix_market_prices_clean_company_id'), 'market_prices_clean', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_prices_clean_period_end'), 'market_prices_clean', ['period_end'], unique=False)
    op.create_index(op.f('ix_market_prices_clean_source_id'), 'market_prices_clean', ['source_id'], unique=False)
    op.create_index(op.f('ix_market_prices_clean_trade_date'), 'market_prices_clean', ['trade_date'], unique=False)
    op.create_table('market_prices_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('transaction_value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('transaction_frequency', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'trade_date', 'source_id', name='uq_price_raw_company_date_source')
    )
    op.create_index(op.f('ix_market_prices_raw_available_at'), 'market_prices_raw', ['available_at'], unique=False)
    op.create_index(op.f('ix_market_prices_raw_company_id'), 'market_prices_raw', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_prices_raw_period_end'), 'market_prices_raw', ['period_end'], unique=False)
    op.create_index(op.f('ix_market_prices_raw_source_id'), 'market_prices_raw', ['source_id'], unique=False)
    op.create_index(op.f('ix_market_prices_raw_trade_date'), 'market_prices_raw', ['trade_date'], unique=False)
    op.create_table('model_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('branch', sa.String(length=24), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_features_as_of_date'), 'model_features', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_model_features_company_id'), 'model_features', ['company_id'], unique=False)
    op.create_table('news_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_entities_article_id'), 'news_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_entities_company_id'), 'news_entities', ['company_id'], unique=False)
    op.create_table('news_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=24), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('event_category', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('novelty', sa.String(length=16), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('impact_horizon', sa.String(length=16), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiment_article_id'), 'news_sentiment', ['article_id'], unique=False)
    op.create_index(op.f('ix_news_sentiment_company_id'), 'news_sentiment', ['company_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainty', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_as_of_date'), 'predictions', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_predictions_company_id'), 'predictions', ['company_id'], unique=False)
    op.create_index(op.f('ix_predictions_horizon'), 'predictions', ['horizon'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_table('recommendation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('guardrails_triggered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_zone', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('investment_style', sa.String(length=32), nullable=True),
    sa.Column('suggested_horizon', sa.String(length=32), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_results_as_of_date'), 'recommendation_results', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_recommendation_results_company_id'), 'recommendation_results', ['company_id'], unique=False)
    op.create_table('reputation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('potential_impact', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('related_article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['related_article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_events_available_at'), 'reputation_events', ['available_at'], unique=False)
    op.create_index(op.f('ix_reputation_events_category'), 'reputation_events', ['category'], unique=False)
    op.create_index(op.f('ix_reputation_events_company_id'), 'reputation_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_reputation_events_period_end'), 'reputation_events', ['period_end'], unique=False)
    op.create_index(op.f('ix_reputation_events_source_id'), 'reputation_events', ['source_id'], unique=False)
    op.create_table('sector_specific_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('sector_registry_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('value_text', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['sector_registry_id'], ['sector_registry.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_specific_metrics_available_at'), 'sector_specific_metrics', ['available_at'], unique=False)
    op.create_index(op.f('ix_sector_specific_metrics_company_id'), 'sector_specific_metrics', ['company_id'], unique=False)
    op.create_index(op.f('ix_sector_specific_metrics_metric_name'), 'sector_specific_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_sector_specific_metrics_period_end'), 'sector_specific_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_sector_specific_metrics_sector_registry_id'), 'sector_specific_metrics', ['sector_registry_id'], unique=False)
    op.create_index(op.f('ix_sector_specific_metrics_source_id'), 'sector_specific_metrics', ['source_id'], unique=False)
    op.create_table('technical_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('feature_date', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_features_company_id'), 'technical_features', ['company_id'], unique=False)
    op.create_index(op.f('ix_technical_features_feature_date'), 'technical_features', ['feature_date'], unique=False)
    op.create_index(op.f('ix_technical_features_feature_name'), 'technical_features', ['feature_name'], unique=False)
    op.create_table('valuation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('methods_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fair_value_bear', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fair_value_base', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fair_value_bull', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fair_value_conservative', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sensitivity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_results_as_of_date'), 'valuation_results', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_valuation_results_company_id'), 'valuation_results', ['company_id'], unique=False)
    op.create_table('financial_statement_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('statement_section', sa.String(length=32), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('account_name_reported', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('available_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_restated', sa.Boolean(), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'VALID', 'SUSPECT', 'INVALID', 'INSUFFICIENT', name='quality_status'), nullable=False),
    sa.Column('raw_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['data_source_registry.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['financial_statements_raw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statement_items_available_at'), 'financial_statement_items', ['available_at'], unique=False)
    op.create_index(op.f('ix_financial_statement_items_company_id'), 'financial_statement_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_statement_items_period_end'), 'financial_statement_items', ['period_end'], unique=False)
    op.create_index(op.f('ix_financial_statement_items_source_id'), 'financial_statement_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_financial_statement_items_statement_id'), 'financial_statement_items', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_statement_items_statement_id'), table_name='financial_statement_items')
    op.drop_index(op.f('ix_financial_statement_items_source_id'), table_name='financial_statement_items')
    op.drop_index(op.f('ix_financial_statement_items_period_end'), table_name='financial_statement_items')
    op.drop_index(op.f('ix_financial_statement_items_company_id'), table_name='financial_statement_items')
    op.drop_index(op.f('ix_financial_statement_items_available_at'), table_name='financial_statement_items')
    op.drop_table('financial_statement_items')
    op.drop_index(op.f('ix_valuation_results_company_id'), table_name='valuation_results')
    op.drop_index(op.f('ix_valuation_results_as_of_date'), table_name='valuation_results')
    op.drop_table('valuation_results')
    op.drop_index(op.f('ix_technical_features_feature_name'), table_name='technical_features')
    op.drop_index(op.f('ix_technical_features_feature_date'), table_name='technical_features')
    op.drop_index(op.f('ix_technical_features_company_id'), table_name='technical_features')
    op.drop_table('technical_features')
    op.drop_index(op.f('ix_sector_specific_metrics_source_id'), table_name='sector_specific_metrics')
    op.drop_index(op.f('ix_sector_specific_metrics_sector_registry_id'), table_name='sector_specific_metrics')
    op.drop_index(op.f('ix_sector_specific_metrics_period_end'), table_name='sector_specific_metrics')
    op.drop_index(op.f('ix_sector_specific_metrics_metric_name'), table_name='sector_specific_metrics')
    op.drop_index(op.f('ix_sector_specific_metrics_company_id'), table_name='sector_specific_metrics')
    op.drop_index(op.f('ix_sector_specific_metrics_available_at'), table_name='sector_specific_metrics')
    op.drop_table('sector_specific_metrics')
    op.drop_index(op.f('ix_reputation_events_source_id'), table_name='reputation_events')
    op.drop_index(op.f('ix_reputation_events_period_end'), table_name='reputation_events')
    op.drop_index(op.f('ix_reputation_events_company_id'), table_name='reputation_events')
    op.drop_index(op.f('ix_reputation_events_category'), table_name='reputation_events')
    op.drop_index(op.f('ix_reputation_events_available_at'), table_name='reputation_events')
    op.drop_table('reputation_events')
    op.drop_index(op.f('ix_recommendation_results_company_id'), table_name='recommendation_results')
    op.drop_index(op.f('ix_recommendation_results_as_of_date'), table_name='recommendation_results')
    op.drop_table('recommendation_results')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_horizon'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_company_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_as_of_date'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_news_sentiment_company_id'), table_name='news_sentiment')
    op.drop_index(op.f('ix_news_sentiment_article_id'), table_name='news_sentiment')
    op.drop_table('news_sentiment')
    op.drop_index(op.f('ix_news_entities_company_id'), table_name='news_entities')
    op.drop_index(op.f('ix_news_entities_article_id'), table_name='news_entities')
    op.drop_table('news_entities')
    op.drop_index(op.f('ix_model_features_company_id'), table_name='model_features')
    op.drop_index(op.f('ix_model_features_as_of_date'), table_name='model_features')
    op.drop_table('model_features')
    op.drop_index(op.f('ix_market_prices_raw_trade_date'), table_name='market_prices_raw')
    op.drop_index(op.f('ix_market_prices_raw_source_id'), table_name='market_prices_raw')
    op.drop_index(op.f('ix_market_prices_raw_period_end'), table_name='market_prices_raw')
    op.drop_index(op.f('ix_market_prices_raw_company_id'), table_name='market_prices_raw')
    op.drop_index(op.f('ix_market_prices_raw_available_at'), table_name='market_prices_raw')
    op.drop_table('market_prices_raw')
    op.drop_index(op.f('ix_market_prices_clean_trade_date'), table_name='market_prices_clean')
    op.drop_index(op.f('ix_market_prices_clean_source_id'), table_name='market_prices_clean')
    op.drop_index(op.f('ix_market_prices_clean_period_end'), table_name='market_prices_clean')
    op.drop_index(op.f('ix_market_prices_clean_company_id'), table_name='market_prices_clean')
    op.drop_index(op.f('ix_market_prices_clean_available_at'), table_name='market_prices_clean')
    op.drop_table('market_prices_clean')
    op.drop_index(op.f('ix_fundamental_features_feature_name'), table_name='fundamental_features')
    op.drop_index(op.f('ix_fundamental_features_company_id'), table_name='fundamental_features')
    op.drop_index(op.f('ix_fundamental_features_as_of_date'), table_name='fundamental_features')
    op.drop_table('fundamental_features')
    op.drop_index(op.f('ix_financial_statements_raw_source_id'), table_name='financial_statements_raw')
    op.drop_index(op.f('ix_financial_statements_raw_period_end'), table_name='financial_statements_raw')
    op.drop_index(op.f('ix_financial_statements_raw_company_id'), table_name='financial_statements_raw')
    op.drop_index(op.f('ix_financial_statements_raw_available_at'), table_name='financial_statements_raw')
    op.drop_table('financial_statements_raw')
    op.drop_index(op.f('ix_financial_ratios_source_id'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_ratio_name'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_period_end'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_company_id'), table_name='financial_ratios')
    op.drop_index(op.f('ix_financial_ratios_available_at'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index(op.f('ix_dividends_source_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_period_end'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_ex_date'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_company_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_available_at'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_corporate_actions_source_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_period_end'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_company_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_available_at'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_news_articles_source_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_period_end'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_media_name'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_available_at'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_model_versions_model_name'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_macro_series_source_id'), table_name='macro_series')
    op.drop_index(op.f('ix_macro_series_series_code'), table_name='macro_series')
    op.drop_index(op.f('ix_macro_series_period_end'), table_name='macro_series')
    op.drop_index(op.f('ix_macro_series_observation_date'), table_name='macro_series')
    op.drop_index(op.f('ix_macro_series_available_at'), table_name='macro_series')
    op.drop_table('macro_series')
    op.drop_index(op.f('ix_industry_series_source_id'), table_name='industry_series')
    op.drop_index(op.f('ix_industry_series_series_code'), table_name='industry_series')
    op.drop_index(op.f('ix_industry_series_period_end'), table_name='industry_series')
    op.drop_index(op.f('ix_industry_series_observation_date'), table_name='industry_series')
    op.drop_index(op.f('ix_industry_series_available_at'), table_name='industry_series')
    op.drop_table('industry_series')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_training_runs_model_name'), table_name='training_runs')
    op.drop_table('training_runs')
    op.drop_table('sector_registry')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_name'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_data_source_registry_category'), table_name='data_source_registry')
    op.drop_table('data_source_registry')
    op.drop_index(op.f('ix_data_quality_results_table_name'), table_name='data_quality_results')
    op.drop_index(op.f('ix_data_quality_results_pipeline_run_id'), table_name='data_quality_results')
    op.drop_table('data_quality_results')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
