"""add data_sources capability audit registry

Revision ID: 77eab1ada604
Revises: eddbc2edbbeb
Create Date: 2026-07-26 17:14:21.540770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77eab1ada604'
down_revision: Union[str, Sequence[str], None] = 'eddbc2edbbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_code', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=256), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('API', 'HTML', 'XLSX', 'CSV', 'ZIP', 'XBRL', 'XML', 'RSS', 'PDF', 'DOCUMENT_REPOSITORY', name='source_type'), nullable=False),
    sa.Column('data_category', sa.String(length=32), nullable=False),
    sa.Column('authority_level', sa.Enum('REGULATOR', 'EXCHANGE', 'ISSUER', 'GOVERNMENT', 'INTERNATIONAL_INSTITUTION', 'NEWS_AGENCY', 'BUSINESS_MEDIA', 'GENERAL_MEDIA', 'AGGREGATOR', 'UNOFFICIAL_PROVIDER', name='authority_level'), nullable=False),
    sa.Column('usage_mode', sa.Enum('PRODUCTION_ALLOWED', 'RESEARCH_ONLY', 'METADATA_ONLY', 'VERIFICATION_ONLY', 'LICENSE_REVIEW', name='source_usage_mode'), nullable=False),
    sa.Column('official_status', sa.String(length=32), nullable=False),
    sa.Column('license_status', sa.String(length=32), nullable=False),
    sa.Column('access_method', sa.String(length=32), nullable=False),
    sa.Column('requires_api_key', sa.Boolean(), nullable=False),
    sa.Column('supports_history', sa.Boolean(), nullable=False),
    sa.Column('supports_incremental', sa.Boolean(), nullable=False),
    sa.Column('supports_commercial_use', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.Enum('HEALTHY', 'DEGRADED', 'BLOCKED', 'EMPTY', 'FORMAT_CHANGED', 'RATE_LIMITED', 'AUTHENTICATION_REQUIRED', 'UNVERIFIED', name='source_health_status'), nullable=False),
    sa.Column('last_success_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_failure_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_data_category'), 'data_sources', ['data_category'], unique=False)
    op.create_index(op.f('ix_data_sources_source_code'), 'data_sources', ['source_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sources_source_code'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_data_category'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
