"""market data multi-provider capability, yahoo fallback, quarantine, reconciliation

Revision ID: 8fd61e668b57
Revises: 0584a8d79225
Create Date: 2026-07-25 00:11:53.319678

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8fd61e668b57"
down_revision: str | Sequence[str] | None = "0584a8d79225"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_provider_symbols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_symbol", sa.String(length=32), nullable=False),
        sa.Column("exchange", sa.String(length=16), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_id", "provider", name="uq_company_provider"),
    )
    op.create_index(
        op.f("ix_company_provider_symbols_company_id"),
        "company_provider_symbols",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "market_data_reconciliation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("trading_date", sa.Date(), nullable=False),
        sa.Column("primary_provider", sa.String(length=32), nullable=False),
        sa.Column("verification_provider", sa.String(length=32), nullable=False),
        sa.Column("primary_close", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("verification_close", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("absolute_difference", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("percentage_difference", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("volume_difference", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_data_reconciliation_company_id"),
        "market_data_reconciliation",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_data_reconciliation_trading_date"),
        "market_data_reconciliation",
        ["trading_date"],
        unique=False,
    )
    op.create_table(
        "market_price_quarantine",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=True),
        sa.Column("raw_row", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ingestion_run_id", sa.String(length=64), nullable=True),
        sa.Column("found_at", sa.DateTime(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_price_quarantine_company_id"), "market_price_quarantine", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_price_quarantine_ingestion_run_id"),
        "market_price_quarantine",
        ["ingestion_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_price_quarantine_ticker"), "market_price_quarantine", ["ticker"], unique=False
    )
    op.add_column("corporate_actions", sa.Column("cum_date", sa.Date(), nullable=True))
    op.add_column("corporate_actions", sa.Column("record_date", sa.Date(), nullable=True))
    op.add_column("corporate_actions", sa.Column("payment_date", sa.Date(), nullable=True))
    op.add_column("corporate_actions", sa.Column("effective_date", sa.Date(), nullable=True))
    op.add_column(
        "corporate_actions", sa.Column("cash_amount", sa.Numeric(precision=18, scale=4), nullable=True)
    )
    op.add_column(
        "corporate_actions", sa.Column("split_from", sa.Numeric(precision=18, scale=6), nullable=True)
    )
    op.add_column(
        "corporate_actions", sa.Column("split_to", sa.Numeric(precision=18, scale=6), nullable=True)
    )
    op.add_column("corporate_actions", sa.Column("source_provider", sa.String(length=64), nullable=True))
    op.add_column("corporate_actions", sa.Column("source_url", sa.String(length=1024), nullable=True))
    op.add_column("corporate_actions", sa.Column("verification_status", sa.String(length=24), nullable=False))
    op.add_column(
        "corporate_actions", sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True)
    )
    op.create_index(
        op.f("ix_corporate_actions_action_type"), "corporate_actions", ["action_type"], unique=False
    )
    op.add_column(
        "market_prices_raw",
        sa.Column("adjusted_close_provider", sa.Numeric(precision=18, scale=4), nullable=True),
    )
    op.add_column(
        "market_prices_raw", sa.Column("provider_adjustment_status", sa.String(length=48), nullable=True)
    )
    op.add_column("market_prices_raw", sa.Column("provider_symbol", sa.String(length=32), nullable=True))
    op.add_column("market_prices_raw", sa.Column("exchange", sa.String(length=16), nullable=True))
    op.add_column("market_prices_raw", sa.Column("interval", sa.String(length=16), nullable=False))
    op.add_column("market_prices_raw", sa.Column("usage_restriction", sa.String(length=24), nullable=False))
    op.add_column("market_prices_raw", sa.Column("verification_status", sa.String(length=24), nullable=False))
    op.add_column("market_prices_raw", sa.Column("adjustment_source", sa.String(length=32), nullable=True))
    op.add_column("market_prices_raw", sa.Column("ingestion_run_id", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_market_prices_raw_ingestion_run_id"), "market_prices_raw", ["ingestion_run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_prices_raw_ingestion_run_id"), table_name="market_prices_raw")
    op.drop_column("market_prices_raw", "ingestion_run_id")
    op.drop_column("market_prices_raw", "adjustment_source")
    op.drop_column("market_prices_raw", "verification_status")
    op.drop_column("market_prices_raw", "usage_restriction")
    op.drop_column("market_prices_raw", "interval")
    op.drop_column("market_prices_raw", "exchange")
    op.drop_column("market_prices_raw", "provider_symbol")
    op.drop_column("market_prices_raw", "provider_adjustment_status")
    op.drop_column("market_prices_raw", "adjusted_close_provider")
    op.drop_index(op.f("ix_corporate_actions_action_type"), table_name="corporate_actions")
    op.drop_column("corporate_actions", "confidence")
    op.drop_column("corporate_actions", "verification_status")
    op.drop_column("corporate_actions", "source_url")
    op.drop_column("corporate_actions", "source_provider")
    op.drop_column("corporate_actions", "split_to")
    op.drop_column("corporate_actions", "split_from")
    op.drop_column("corporate_actions", "cash_amount")
    op.drop_column("corporate_actions", "effective_date")
    op.drop_column("corporate_actions", "payment_date")
    op.drop_column("corporate_actions", "record_date")
    op.drop_column("corporate_actions", "cum_date")
    op.drop_index(op.f("ix_market_price_quarantine_ticker"), table_name="market_price_quarantine")
    op.drop_index(op.f("ix_market_price_quarantine_ingestion_run_id"), table_name="market_price_quarantine")
    op.drop_index(op.f("ix_market_price_quarantine_company_id"), table_name="market_price_quarantine")
    op.drop_table("market_price_quarantine")
    op.drop_index(op.f("ix_market_data_reconciliation_trading_date"), table_name="market_data_reconciliation")
    op.drop_index(op.f("ix_market_data_reconciliation_company_id"), table_name="market_data_reconciliation")
    op.drop_table("market_data_reconciliation")
    op.drop_index(op.f("ix_company_provider_symbols_company_id"), table_name="company_provider_symbols")
    op.drop_table("company_provider_symbols")
    # ### end Alembic commands ###
